version: "3"

services:
  rng:
    image: ${REGISTRY}/rng:${TAG-latest}
    ports:
    - "8001:80"

  hasher:
    image: ${REGISTRY}/hasher:${TAG-latest}
    ports:
    - "8002:80"

  webui:
    image: ${REGISTRY}/webui:${TAG-latest}
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"

  worker:
    image: ${REGISTRY}/worker:${TAG-latest}

  redis:
    image: redis

    #registry:
    #image: registry
    #ports:
    #  - "5000:5000"

  debug:
    image: nicolaka/netshoot

networks:
  default:
    driver: overlay

