version: "3"

services:
  rng:
    image: rng
    ports:
    - "8001:80"

  hasher:
    image: hasher
    ports:
    - "8002:80"

  webui:
    image: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"

  worker:
    image: worker

  redis:
    image: redis

    #registry:
    #image: registry
    #ports:
    #  - "5000:5000"

  debug:
    image: nicolaka/netshoot

networks:
  default:
    driver: overlay

